substitutions:
  _REGION: asia-south1
  _REPOSITORY: cv-job-matcher
  _TAG: manual

steps:
  - id: build-api
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - --file
      - docker/Dockerfile.api
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api:${_TAG}
      - .

  - id: build-crawler
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - --file
      - docker/Dockerfile.crawler
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/crawler:${_TAG}
      - .

  - id: build-matcher
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - --file
      - docker/Dockerfile.matcher
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/matcher:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/api:${_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/crawler:${_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/matcher:${_TAG}

timeout: 3600s
